-- Current Chitransh Auto Deal inventory seed.
-- Run after supabase/schema.sql.
-- Prices/images are not provided yet, so price is set to 0 and the UI shows "Price on request".

insert into public.cars (
  name,
  brand,
  model,
  year,
  price,
  odometer,
  fuel_type,
  transmission,
  insurance_active,
  owner_type,
  registration_number,
  description,
  features,
  status
) values
(
  'Hyundai i20 Sportz',
  'Hyundai',
  'i20 Sportz',
  2018,
  0,
  65164,
  'Diesel',
  'Manual',
  true,
  '1st Owner',
  'Registration on request',
  'Well maintained Hyundai i20 Sportz diesel. New tyres and running insurance.',
  array['New tyres', 'Running insurance', 'Well maintained car'],
  'available'
),
(
  'Toyota Fortuner 3.0 4x4 MT',
  'Toyota',
  'Fortuner 3.0 4x4 MT',
  2010,
  0,
  115000,
  'Diesel',
  'Manual',
  false,
  '2nd Owner',
  'RJ06',
  'Silver Toyota Fortuner 3.0 4x4 manual with full-time 4WD, cushioned seats, and tan brown/beige interiors. Insurance date mentioned till 26 Feb 2024.',
  array['Full-time 4WD', 'Auto climate control', 'Silver colour', 'New tyres', 'Cushioned seats', 'Tan brown and beige interiors'],
  'available'
),
(
  'Hyundai Creta SX',
  'Hyundai',
  'Creta 1.6 SX',
  2017,
  0,
  0,
  'Diesel',
  'Manual',
  true,
  '1st Owner',
  'RJ20',
  'White Hyundai Creta SX 1.6. First owner car with new tyres and running insurance.',
  array['White colour', 'New tyres', 'Running insurance', '1.6 SX model'],
  'available'
),
(
  'Tata Harrier XZ',
  'Tata',
  'Harrier XZ',
  2019,
  0,
  98000,
  'Diesel',
  'Manual',
  true,
  '1st Owner',
  'Registration on request',
  'Tata Harrier XZ with running insurance, new tyres, and sunroof.',
  array['Sunroof', 'New tyres', 'Running insurance'],
  'available'
),
(
  'Mahindra Thar 4x4 LX Hard Top',
  'Mahindra',
  'Thar 4x4 LX Hard Top',
  2022,
  0,
  51733,
  'Diesel',
  'Manual',
  true,
  '1st Owner',
  'Registration on request',
  'Mahindra Thar 4x4 LX hard top diesel with company record, running insurance, and four new tyres.',
  array['4x4', 'Hard top', 'Company record', 'Running insurance', 'Four new tyres', 'Well maintained car'],
  'available'
),
(
  'Hyundai Creta E',
  'Hyundai',
  'Creta E',
  2022,
  0,
  73305,
  'Diesel',
  'Manual',
  true,
  '1st Owner',
  'Registration on request',
  'Hyundai Creta E diesel with company record, running insurance, and well maintained condition.',
  array['Company record', 'Running insurance', 'Well maintained car'],
  'available'
),
(
  'Maruti Suzuki Swift VDI',
  'Maruti Suzuki',
  'Swift VDI',
  2014,
  0,
  0,
  'Diesel',
  'Manual',
  false,
  'Owner on request',
  'Registration on request',
  'Maruti Suzuki Swift VDI diesel. New tyres.',
  array['New tyres', 'Diesel'],
  'available'
);
